### ISSUE TITLE
Could not pass step 1

### ISSUE THREAD

**Issue by DorjM** [AbuseIO/abuseio-docker#2]
Hi,

I could install abuseio-docker and below is error msg.

Error parsing reference: "ubuntu:16.04 as intermediate" is not a valid repository/tag: invalid reference format.

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

**Comment by joverthegrey** [comment]
Hi @chinguunhr, 
We use a multi stage build in the dockerfile, docker 17.05 or higher is required for this.
Xenial (16.04) has an older version of docker, you can add the official docker repositories as described here : https://docs.docker.com/install/linux/docker-ce/ubuntu/

regards,
Joost

**Comment by DorjM** [comment]
@joverthegrey  Thanks. Its working now.
Another question. :)
Do you know how can we retrive email from OWA ? (We cannot enable IMAP)

**Comment by joverthegrey** [comment]
A bit out of scope ;) but I've had some success with davmail (http://davmail.sourceforge.net/) which will act as an IMAP proxy for OWA. You can run it on a server and use fetchmail to connect to it.

For config specifics google can help you, the standard settings we found worked for us.

Regards

**Comment by marknl** [comment]
You can even run it inside a docker ;-)

https://hub.docker.com/r/jberrenberg/davmail/

**Comment by DorjM** [comment]
@marknl  , @joverthegrey  thanks.
